/* eslint-disable prettier/prettier */
export enum Permission {
  CENTRAL_ASIGNAR_CONTRASEÑA = 'CENTRAL_ESTABLECER_CONTRASEÑA_USUARIO',
  CENTRAL_ASIGNAR_APLICACION = 'CENTRAL_ESTABLECER_APP_USUARIO',
  CENTRAL_ASIGNAR_ROL = 'CENTRAL_ESTABLECER_ROL_USUARIO',
  CENTRAL_REMOVER_ROL_USUARIO = 'CENTRAL_REMOVER_ROL_USUARIO',

  CENTRAL_CREAR_ROL = 'CENTRAL_CREAR_ROL', 
  CENTRAL_EDITAR_ROL = 'CENTRAL_EDITAR_ROL',
  CENTRAL_ASIGNAR_PERMISO_ROL = 'CENTRAL_ESTABLECER_PERMISO_ROL',
  CENTRAL_ELIMINAR_PERMISO_ROL = 'CENTRAL_ELIMINAR_PERMISO_ROL',
  CENTRAL_ELIMINAR_ROL = 'CENTRAL_ELIMINAR_ROL',
  
  CENTRAL_CREAR_PERMISO = 'CENTRAL_CREAR_PERMISO',
  CENTRAL_EDITAR_PERMISO = 'CENTRAL_EDITAR_PERMISO',
  CENTRAL_ELIMINAR_PERMISO = 'CENTRAL_ELIMINAR_PERMISO',
 
  CENTRAL_CREAR_APP = 'CENTRAL_CREAR_APP',
  CENTRAL_EDITAR_APP = 'CENTRAL_EDITAR_APP',
  CENTRAL_ELIMINAR_APP = 'CENTRAL_ELIMINAR_APP',
  CENTRAL_RESTABLECER_APP = 'CENTRAL_RESTABLECER_APP',
}

